name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.GIT_GITHUB_TOKEN }}
      - name: Bump version & release
        run: |
          tag=${GITHUB_REF#refs/tags/}
          sed -i -r "s/(version = )\"[0-9]+.[0-9]+.[0-9]+\"/\1\"$tag\"/" plugin.toml
          git config user.name "${{ secrets.GIT_NAME }}"
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git add .
          git commit -m "Release version $tag"
          git push
