name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Lint & run tests
    strategy:
      matrix:
        dokku-version: ["v0.21.4", "v0.22.0"]
    steps:
      - uses: actions/checkout@v1
      - name: Install test tools
        run: sudo apt-get install -y bats shellcheck
      - name: Lint
        run: make lint
      - name: Install dokku
        run: |
          wget https://raw.githubusercontent.com/dokku/dokku/$DOKKU_VERSION/bootstrap.sh
          sudo DOKKU_TAG="$DOKKU_VERSION" bash bootstrap.sh
        env:
          DOKKU_VERSION: ${{ matrix.dokku-version }}
      - name: Install discourse plugin
        run: |
          sudo dokku plugin:install file:///$(pwd) discourse
      - name: Run tests
        run: sudo make test
